# Form implementation generated from reading ui file 'C:\Users\irsha\PycharmProjects\FAFT\CasePrices.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CasePrices(object):
    def setupUi(self, CasePrices):
        CasePrices.setObjectName("CasePrices")
        CasePrices.resize(391, 412)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\irsha\\PycharmProjects\\FAFT\\icon.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        CasePrices.setWindowIcon(icon)
        CasePrices.setStyleSheet("QDialog {\n"
"    background-color: #232323;\n"
"}")
        self.gridLayoutWidget = QtWidgets.QWidget(CasePrices)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 391, 361))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setStyleSheet("QLabel {\n"
"    background-color: gold;\n"
"    width: 75px;\n"
"    height: 50px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setStyleSheet("QLabel {\n"
"    background-color: gold;\n"
"    width: 75px;\n"
"    height: 50px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setStyleSheet("QLabel {\n"
"    background-color: gold;\n"
"    width: 75px;\n"
"    height: 50px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setStyleSheet("QLabel {\n"
"    background-color: gold;\n"
"    width: 75px;\n"
"    height: 50px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setStyleSheet("QLabel {\n"
"    background-color: gold;\n"
"    width: 75px;\n"
"    height: 50px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setStyleSheet("QLabel {\n"
"    background-color: gold;\n"
"    width: 75px;\n"
"    height: 50px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setStyleSheet("QLabel {\n"
"    background-color: gold;\n"
"    width: 75px;\n"
"    height: 50px;\n"
"    font-size: 40px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setStyleSheet("QLabel {\n"
"    background-color: gold;\n"
"    width: 75px;\n"
"    height: 50px;\n"
"    font-size: 40px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setStyleSheet("QLabel {\n"
"    background-color: gold;\n"
"    width: 75px;\n"
"    height: 50px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"")
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setStyleSheet("QLabel {\n"
"    background-color: gold;\n"
"    width: 75px;\n"
"    height: 50px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"")
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setStyleSheet("QLabel {\n"
"    background-color: gold;\n"
"    width: 75px;\n"
"    height: 50px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"")
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 3, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setStyleSheet("QLabel {\n"
"    background-color: gold;\n"
"    width: 75px;\n"
"    height: 50px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"")
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 4, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setStyleSheet("QLabel {\n"
"    background-color: gold;\n"
"    width: 75px;\n"
"    height: 50px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"")
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 5, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_14.setStyleSheet("QLabel {\n"
"    background-color: gold;\n"
"    width: 75px;\n"
"    height: 50px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"")
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 6, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(CasePrices)
        self.pushButton.setGeometry(QtCore.QRect(140, 370, 111, 41))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: gold;\n"
"    width: 75px;\n"
"    height: 50px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: orange;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: yellow;\n"
"}")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(CasePrices)
        QtCore.QMetaObject.connectSlotsByName(CasePrices)

    def retranslateUi(self, CasePrices):
        _translate = QtCore.QCoreApplication.translate
        CasePrices.setWindowTitle(_translate("CasePrices", "Dialog"))
        self.label_3.setText(_translate("CasePrices", "Змеиный укус:"))
        self.label_5.setText(_translate("CasePrices", "Кейс Грёзы и Кошмары:"))
        self.label_7.setText(_translate("CasePrices", "Призма 2 Кейс:"))
        self.label_4.setText(_translate("CasePrices", "Кейс Разлом:"))
        self.label.setText(_translate("CasePrices", "Гремучий кейс:"))
        self.label_6.setText(_translate("CasePrices", "Кейс Решающий момент:"))
        self.label_2.setText(_translate("CasePrices", "    Кейс"))
        self.label_8.setText(_translate("CasePrices", "    Цена"))
        self.label_9.setText(_translate("CasePrices", "-"))
        self.label_10.setText(_translate("CasePrices", "-"))
        self.label_11.setText(_translate("CasePrices", "-"))
        self.label_12.setText(_translate("CasePrices", "-"))
        self.label_13.setText(_translate("CasePrices", "-"))
        self.label_14.setText(_translate("CasePrices", "-"))
        self.pushButton.setText(_translate("CasePrices", "Обновить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CasePrices = QtWidgets.QDialog()
    ui = Ui_CasePrices()
    ui.setupUi(CasePrices)
    CasePrices.show()
    sys.exit(app.exec())
