# Form implementation generated from reading ui file 'C:\Users\irsha\PycharmProjects\FAFT\FAFTUI.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FAFTUI(object):
    def setupUi(self, FAFTUI):
        FAFTUI.setObjectName("FAFTUI")
        FAFTUI.resize(768, 670)
        font = QtGui.QFont()
        font.setPointSize(10)
        FAFTUI.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\irsha\\PycharmProjects\\FAFT\\../../Downloads/icon.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        FAFTUI.setWindowIcon(icon)
        FAFTUI.setStyleSheet("QDialog {\n"
"    background-color: #232323;\n"
"}")
        self.verticalLayoutWidget = QtWidgets.QWidget(FAFTUI)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 180, 271, 276))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sendall = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.sendall.setStyleSheet("QPushButton {\n"
"    background-color: gold;\n"
"    width: 75px;\n"
"    height: 50px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: orange;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: yellow;\n"
"}")
        self.sendall.setObjectName("sendall")
        self.verticalLayout.addWidget(self.sendall)
        self.PriceButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.PriceButton.setStyleSheet("QPushButton {\n"
"    background-color: gold;\n"
"    width: 75px;\n"
"    height: 50px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: orange;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: yellow;\n"
"}")
        self.PriceButton.setObjectName("PriceButton")
        self.verticalLayout.addWidget(self.PriceButton)
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: gold;\n"
"    width: 75px;\n"
"    height: 50px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: orange;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: yellow;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: gold;\n"
"    width: 75px;\n"
"    height: 50px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: orange;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: yellow;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: gold;\n"
"    width: 75px;\n"
"    height: 50px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: orange;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: yellow;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.main = QtWidgets.QLabel(FAFTUI)
        self.main.setGeometry(QtCore.QRect(50, 10, 651, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.main.setFont(font)
        self.main.setStyleSheet("QLabel {\n"
"    color: silver;\n"
"    font-weight: bold;\n"
"    font-size: 25px;\n"
"}")
        self.main.setObjectName("main")
        self.commands = QtWidgets.QLabel(FAFTUI)
        self.commands.setGeometry(QtCore.QRect(30, 150, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.commands.setFont(font)
        self.commands.setStyleSheet("QLabel {\n"
"    color: silver;\n"
"    font-weight: bold;\n"
"    font-size: 25px;\n"
"}")
        self.commands.setObjectName("commands")
        self.clients = QtWidgets.QLabel(FAFTUI)
        self.clients.setGeometry(QtCore.QRect(480, 80, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.clients.setFont(font)
        self.clients.setStyleSheet("QLabel {\n"
"    color: silver;\n"
"    font-weight: bold;\n"
"    font-size: 25px;\n"
"}")
        self.clients.setObjectName("clients")
        self.networse_input = QtWidgets.QLabel(FAFTUI)
        self.networse_input.setGeometry(QtCore.QRect(110, 70, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.networse_input.setFont(font)
        self.networse_input.setStyleSheet("QLabel {\n"
"    color: silver;\n"
"    font-weight: bold;\n"
"    font-size: 25px;\n"
"}")
        self.networse_input.setObjectName("networse_input")
        self.gridLayoutWidget = QtWidgets.QWidget(FAFTUI)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(380, 120, 341, 591))
        self.gridLayoutWidget.setStyleSheet("QPushButton {\n"
"    background-color: gold;\n"
"    width: 75px;\n"
"    height: 50px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    text-align: center;\n"
"\n"
"}\n"
"")
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_20 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_20.setStyleSheet("QPushButton {\n"
"    background-color: gold;\n"
"    width: 75px;\n"
"    height: 50px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: orange;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: yellow;\n"
"}")
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout.addWidget(self.pushButton_20, 3, 2, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_18.setStyleSheet("QPushButton {\n"
"    background-color: gold;\n"
"    width: 75px;\n"
"    height: 50px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: orange;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: yellow;\n"
"}")
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout.addWidget(self.pushButton_18, 3, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    background-color: gold;\n"
"    width: 75px;\n"
"    height: 50px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: orange;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: yellow;\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 4, 0, 1, 1)
        self.client1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.client1.setStyleSheet("QPushButton {\n"
"    background-color: gold;\n"
"    width: 75px;\n"
"    height: 50px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: orange;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: yellow;\n"
"}")
        self.client1.setObjectName("client1")
        self.gridLayout.addWidget(self.client1, 0, 0, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_19.setStyleSheet("QPushButton {\n"
"    background-color: gold;\n"
"    width: 75px;\n"
"    height: 50px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: orange;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: yellow;\n"
"}")
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout.addWidget(self.pushButton_19, 3, 1, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_11.setStyleSheet("QPushButton {\n"
"    background-color: gold;\n"
"    width: 75px;\n"
"    height: 50px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: orange;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: yellow;\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 2, 2, 1, 1)
        self.pushButton_26 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_26.setObjectName("pushButton_26")
        self.gridLayout.addWidget(self.pushButton_26, 6, 0, 1, 1)
        self.pushButton_24 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_24.setObjectName("pushButton_24")
        self.gridLayout.addWidget(self.pushButton_24, 6, 2, 1, 1)
        self.client3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.client3.setStyleSheet("QPushButton {\n"
"    background-color: gold;\n"
"    width: 75px;\n"
"    height: 50px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: orange;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: yellow;\n"
"}")
        self.client3.setObjectName("client3")
        self.gridLayout.addWidget(self.client3, 0, 2, 1, 1)
        self.pushButton_25 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_25.setObjectName("pushButton_25")
        self.gridLayout.addWidget(self.pushButton_25, 6, 1, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout.addWidget(self.pushButton_16, 5, 1, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout.addWidget(self.pushButton_15, 5, 0, 1, 1)
        self.client2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.client2.setStyleSheet("QPushButton {\n"
"    background-color: gold;\n"
"    width: 75px;\n"
"    height: 50px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: orange;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: yellow;\n"
"}")
        self.client2.setObjectName("client2")
        self.gridLayout.addWidget(self.client2, 0, 1, 1, 1)
        self.client7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.client7.setStyleSheet("QPushButton {\n"
"    background-color: gold;\n"
"    width: 75px;\n"
"    height: 50px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: orange;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: yellow;\n"
"}")
        self.client7.setObjectName("client7")
        self.gridLayout.addWidget(self.client7, 1, 2, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout.addWidget(self.pushButton_17, 5, 2, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_10.setStyleSheet("QPushButton {\n"
"    background-color: gold;\n"
"    width: 75px;\n"
"    height: 50px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: orange;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: yellow;\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 2, 1, 1, 1)
        self.client4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.client4.setStyleSheet("QPushButton {\n"
"    background-color: gold;\n"
"    width: 75px;\n"
"    height: 50px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: orange;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: yellow;\n"
"}")
        self.client4.setObjectName("client4")
        self.gridLayout.addWidget(self.client4, 1, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"    background-color: gold;\n"
"    width: 75px;\n"
"    height: 50px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: orange;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: yellow;\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 2, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background-color: gold;\n"
"    width: 75px;\n"
"    height: 50px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: orange;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: yellow;\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 4, 2, 1, 1)
        self.client6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.client6.setStyleSheet("QPushButton {\n"
"    background-color: gold;\n"
"    width: 75px;\n"
"    height: 50px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: orange;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: yellow;\n"
"}")
        self.client6.setObjectName("client6")
        self.gridLayout.addWidget(self.client6, 1, 1, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    background-color: gold;\n"
"    width: 75px;\n"
"    height: 50px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: orange;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: yellow;\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 4, 1, 1, 1)
        self.networse_2 = QtWidgets.QLineEdit(FAFTUI)
        self.networse_2.setGeometry(QtCore.QRect(20, 110, 201, 31))
        self.networse_2.setText("")
        self.networse_2.setObjectName("networse_2")
        self.pushButton_2 = QtWidgets.QPushButton(FAFTUI)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 610, 221, 31))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: silver;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: lightgrey;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_12 = QtWidgets.QPushButton(FAFTUI)
        self.pushButton_12.setGeometry(QtCore.QRect(0, 640, 241, 31))
        self.pushButton_12.setStyleSheet("QPushButton {\n"
"    background-color: silver;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: lightgrey;\n"
"}")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(FAFTUI)
        self.pushButton_13.setGeometry(QtCore.QRect(0, 580, 161, 31))
        self.pushButton_13.setStyleSheet("QPushButton {\n"
"    background-color: silver;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: lightgrey;\n"
"}")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(FAFTUI)
        self.pushButton_14.setGeometry(QtCore.QRect(220, 110, 71, 31))
        self.pushButton_14.setStyleSheet("QPushButton {\n"
"    background-color: gold;\n"
"    width: 75px;\n"
"    height: 50px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: orange;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: yellow;\n"
"}")
        self.pushButton_14.setObjectName("pushButton_14")

        self.retranslateUi(FAFTUI)
        QtCore.QMetaObject.connectSlotsByName(FAFTUI)

    def retranslateUi(self, FAFTUI):
        _translate = QtCore.QCoreApplication.translate
        FAFTUI.setWindowTitle(_translate("FAFTUI", "CCFApp"))
        self.sendall.setText(_translate("FAFTUI", "Отправить всем"))
        self.PriceButton.setText(_translate("FAFTUI", "Цены кейсов"))
        self.pushButton_4.setText(_translate("FAFTUI", "Калькулятор дохода"))
        self.pushButton_3.setText(_translate("FAFTUI", "Скоро!"))
        self.pushButton.setText(_translate("FAFTUI", "Скоро!"))
        self.main.setText(_translate("FAFTUI", "Добро пожаловать в Бабломёт. (CSGOCASEFARM)\n"
"                             (ADMIN PANEL)"))
        self.commands.setText(_translate("FAFTUI", "Быстрые команды"))
        self.clients.setText(_translate("FAFTUI", "Клиенты"))
        self.networse_input.setText(_translate("FAFTUI", "Доход"))
        self.pushButton_20.setText(_translate("FAFTUI", "PushButton"))
        self.pushButton_18.setText(_translate("FAFTUI", "PushButton"))
        self.pushButton_8.setText(_translate("FAFTUI", "PushButton"))
        self.client1.setText(_translate("FAFTUI", "@twisttyyy"))
        self.pushButton_19.setText(_translate("FAFTUI", "PushButton"))
        self.pushButton_11.setText(_translate("FAFTUI", "PushButton"))
        self.pushButton_26.setText(_translate("FAFTUI", "PushButton"))
        self.pushButton_24.setText(_translate("FAFTUI", "PushButton"))
        self.client3.setText(_translate("FAFTUI", "@INVALID_N..."))
        self.pushButton_25.setText(_translate("FAFTUI", "PushButton"))
        self.pushButton_16.setText(_translate("FAFTUI", "PushButton"))
        self.pushButton_15.setText(_translate("FAFTUI", "PushButton"))
        self.client2.setText(_translate("FAFTUI", "@sashoooooookkkk"))
        self.client7.setText(_translate("FAFTUI", "PushButton"))
        self.pushButton_17.setText(_translate("FAFTUI", "PushButton"))
        self.pushButton_10.setText(_translate("FAFTUI", "PushButton"))
        self.client4.setText(_translate("FAFTUI", "PushButton"))
        self.pushButton_9.setText(_translate("FAFTUI", "PushButton"))
        self.pushButton_6.setText(_translate("FAFTUI", "PushButton"))
        self.client6.setText(_translate("FAFTUI", "PushButton"))
        self.pushButton_7.setText(_translate("FAFTUI", "PushButton"))
        self.pushButton_2.setText(_translate("FAFTUI", "https://t.me/csgofarmbot"))
        self.pushButton_12.setText(_translate("FAFTUI", "https://t.me/csgocasefarmbot"))
        self.pushButton_13.setText(_translate("FAFTUI", "https://t.me/ZiFlux"))
        self.pushButton_14.setText(_translate("FAFTUI", "Ввод"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FAFTUI = QtWidgets.QDialog()
    ui = Ui_FAFTUI()
    ui.setupUi(FAFTUI)
    FAFTUI.show()
    sys.exit(app.exec())
